# See: https://gohugo.io/getting-started/configuration/#merge-configuration-from-themes
_merge = "deep"

favicon_mstilecolor = "#603cba"

### BGN: Structured Data ###
  description = "Confident Traveler ğŸ§­ by áœŒáœ“áœƒáœ’ (Yuki ãƒ» é›ªäº®) / Yahuhanan Yukiya Sese Cuneta."
  keywords = ["Confident Traveler", "Confidentraveler", "è‡ªä¿¡ã®ã‚ã‚‹æ—…è¡Œè€…", "ë‹¹ë‹¹í•˜ ì—¬í–‰ì", "ìì‹ ê°ìˆëŠ” ì—¬í–‰ì", "YourOnlyOne", "YourOnly.One", "Yahuhanan Yukiya Sese Cuneta", "Yuki", "YoHan", "Yo-Han", "áœŒáœ“áœƒáœ’", "ì‚¬ìš”í•œ", "è¬é›ªçŸ¢ï¼ˆã‚†ãã‚„ï¼‰", "ìŠ¤ë…¸", "Seu-No", "SeuNo", "Snow", "Yohanan", "áœŒáœ“áœ‘áœˆáœˆáœ”", "áœŒáœ“áœ‘áœˆáœˆáœ•", "áœŒáœ‘áœ“áœ‘áœˆáœˆáœ”", "áœŒáœ‘áœ“áœ‘áœˆáœˆáœ•"] # Can be overriden per page
  images = ["https://rsc.youronly.one/img/y/Confident_Traveler-logo-01-1500x.webp"]
### END: Structured Data ###

### BGN: Theme Settings ###
  message = ""
  hideAutoMenu = false

  # Pagination options
  paginate = 12
  multipage = false

  # Dark mode
  darkMode = true
### END: Theme Settings ###

### BGN: Other Settings ###
  [semweb]
    datecreated = "2021-02-06"
    sameas = [
      "https://www.facebook.com/confidentraveler",
      "https://c.im/@YourOnlyOne",
      "https://pixelfed.social/YourOnlyOne",
      "https://www.youtube.com/@YourOnlyOneOfcl",
      "https://www.facebook.com/YourOnly.ONE.ofcl"
    ]
### END: Other Settings ###
